/** Academic execution workspace seed data */

export const TASK_TYPES = [
  'All',
  'Technical',
  'Academic',
  'Scrum',
  'Interview',
  'Placement',
  'Collaboration',
];

export const TASK_STATUSES = [
  'pending',
  'in_progress',
  'submitted',
  'under_review',
  'completed',
  'overdue',
  'blocked',
];

export const TASKS = [
  {
    id: 't1',
    title: 'React Hooks Assignment — Todo App Refactor',
    type: 'Technical',
    module: 'React & State Management',
    assignedBy: 'Facilitator John',
    priority: 'critical',
    status: 'in_progress',
    dueDate: '2026-05-28',
    estHours: 6,
    progress: 65,
    github: 'linked',
    evalWeight: 15,
    difficulty: 'Advanced',
    impact: 'High',
    attachments: 2,
    description: 'Refactor the provided Todo application using useState, useEffect, and at least one custom hook. Submit via GitHub PR.',
    outcomes: ['Master React hooks lifecycle', 'Implement custom hooks', 'Clean component architecture'],
    resources: ['hooks-cheatsheet.pdf', 'starter-repo'],
    rubric: 'Code quality 40%, Functionality 40%, Documentation 20%',
    instructions: 'Fork the boilerplate repo. All commits must be on feature/hooks-refactor branch.',
    submissions: [{ date: '2026-05-24', status: 'draft', note: 'WIP — useEffect cleanup pending' }],
    comments: [{ author: 'Facilitator John', text: 'Focus on dependency array correctness.', date: 'May 25' }],
  },
  {
    id: 't2',
    title: 'CSS Grid Layout Lab Submission',
    type: 'Technical',
    module: 'HTML/CSS Foundations',
    assignedBy: 'Facilitator John',
    priority: 'high',
    status: 'overdue',
    dueDate: '2026-05-26',
    estHours: 4,
    progress: 90,
    github: 'pending',
    evalWeight: 10,
    difficulty: 'Intermediate',
    impact: 'Medium',
    attachments: 1,
    description: 'Build a responsive dashboard layout using CSS Grid with 12-column system.',
    outcomes: ['Grid template areas', 'Responsive breakpoints'],
    resources: ['grid-guide.pdf'],
    rubric: 'Layout accuracy 50%, Responsiveness 30%, Code 20%',
    instructions: 'Deploy to Netlify and attach live URL.',
    submissions: [],
    comments: [],
  },
  {
    id: 't3',
    title: 'Daily Scrum Update — Blocker Report',
    type: 'Scrum',
    module: 'Week 8 Sprint',
    assignedBy: 'System',
    priority: 'high',
    status: 'pending',
    dueDate: '2026-05-27',
    estHours: 0.5,
    progress: 0,
    github: 'n/a',
    evalWeight: 5,
    difficulty: 'Basic',
    impact: 'High',
    attachments: 0,
    description: 'Submit yesterday progress, today plan, and blockers before 9:30 AM scrum.',
    outcomes: ['Scrum discipline', 'Blocker visibility'],
    resources: ['scrum-template.md'],
    rubric: 'Timeliness 60%, Clarity 40%',
    instructions: 'Use the scrum form in Academics section.',
    submissions: [],
    comments: [],
  },
  {
    id: 't4',
    title: 'DSA Sheet — Arrays & Strings (50 problems)',
    type: 'Interview',
    module: 'Interview Preparation',
    assignedBy: 'Placement Cell',
    priority: 'medium',
    status: 'in_progress',
    dueDate: '2026-06-05',
    estHours: 20,
    progress: 42,
    github: 'n/a',
    evalWeight: 12,
    difficulty: 'Advanced',
    impact: 'High',
    attachments: 3,
    description: 'Complete assigned LeetCode-style problems from the institutional DSA tracker.',
    outcomes: ['Pattern recognition', 'Time complexity analysis'],
    resources: ['dsa-tracker.xlsx', 'video-walkthrough'],
    rubric: 'Problems solved 70%, Explanation quality 30%',
    instructions: 'Log solutions in the shared tracker with Big-O notes.',
    submissions: [{ date: '2026-05-20', status: 'partial', note: '21/50 completed' }],
    comments: [],
  },
  {
    id: 't5',
    title: 'Resume v2 — ATS Optimized',
    type: 'Placement',
    module: 'Career Readiness',
    assignedBy: 'Placement Mentor',
    priority: 'high',
    status: 'under_review',
    dueDate: '2026-05-30',
    estHours: 3,
    progress: 100,
    github: 'n/a',
    evalWeight: 8,
    difficulty: 'Intermediate',
    impact: 'Medium',
    attachments: 1,
    description: 'Update resume with MERN projects, metrics, and ATS-friendly formatting.',
    outcomes: ['Professional resume', 'Project highlights'],
    resources: ['resume-template.docx'],
    rubric: 'Format 30%, Content 50%, Projects 20%',
    instructions: 'Upload PDF to profile documents.',
    submissions: [{ date: '2026-05-25', status: 'submitted', note: 'Awaiting mentor review' }],
    comments: [{ author: 'Placement Mentor', text: 'Add quantified impact to Project 2.', date: 'May 26' }],
  },
  {
    id: 't6',
    title: 'Module 4 Assessment — React Patterns',
    type: 'Academic',
    module: 'React & State Management',
    assignedBy: 'Facilitator John',
    priority: 'critical',
    status: 'pending',
    dueDate: '2026-06-02',
    estHours: 2,
    progress: 0,
    github: 'n/a',
    evalWeight: 20,
    difficulty: 'Intermediate',
    impact: 'Critical',
    attachments: 0,
    description: 'Timed assessment covering hooks, context, and performance patterns.',
    outcomes: ['Validate module mastery'],
    resources: ['revision-notes.pdf'],
    rubric: 'MCQ 40%, Coding 60%',
    instructions: 'Available only during scheduled window. No external resources.',
    submissions: [],
    comments: [],
  },
  {
    id: 't7',
    title: 'Peer Code Review — PR #42',
    type: 'Collaboration',
    module: 'Team Project Alpha',
    assignedBy: 'Team Lead',
    priority: 'medium',
    status: 'submitted',
    dueDate: '2026-05-27',
    estHours: 1,
    progress: 100,
    github: 'linked',
    evalWeight: 5,
    difficulty: 'Basic',
    impact: 'Low',
    attachments: 0,
    description: 'Review teammate PR for authentication module. Provide constructive feedback.',
    outcomes: ['Code review skills', 'Team collaboration'],
    resources: ['review-checklist.md'],
    rubric: 'Quality of feedback 100%',
    instructions: 'Minimum 3 inline comments required on GitHub.',
    submissions: [{ date: '2026-05-26', status: 'submitted', note: '5 comments left' }],
    comments: [],
  },
  {
    id: 't8',
    title: 'API Integration Mini Project',
    type: 'Technical',
    module: 'Node.js Backend',
    assignedBy: 'Facilitator John',
    priority: 'low',
    status: 'blocked',
    dueDate: '2026-06-10',
    estHours: 8,
    progress: 15,
    github: 'linked',
    evalWeight: 12,
    difficulty: 'Advanced',
    impact: 'Medium',
    attachments: 2,
    description: 'Build REST API consumer with error handling and loading states.',
    outcomes: ['API integration', 'Error boundaries'],
    resources: ['api-docs.json', 'postman-collection'],
    rubric: 'Functionality 50%, Error handling 30%, UI 20%',
    instructions: 'Blocked until Module 4 assessment is cleared.',
    submissions: [],
    comments: [{ author: 'Facilitator John', text: 'Complete Module 4 assessment first.', date: 'May 24' }],
  },
];

export const OVERVIEW_STATS = {
  active: 6,
  overdue: 1,
  completedWeek: 4,
  productivityScore: 82,
  sprintCompletion: 68,
  interviewPrep: 42,
  submissionAccuracy: 94,
  consistency: 91,
};

export const RESOURCES = [
  { name: 'Module 4 Handbook', type: 'PDF', module: 'React', size: '2.4 MB', url: '#' },
  { name: 'React Hooks Video Series', type: 'Video', module: 'React', size: '12 lessons', url: '#' },
  { name: 'MERN Boilerplate Repo', type: 'GitHub', module: 'Full Stack', size: 'Repository', url: '#' },
  { name: 'DSA Practice Sheet', type: 'Sheet', module: 'Interview', size: '50 problems', url: '#' },
  { name: 'Scrum Standup Template', type: 'Doc', module: 'Scrum', size: 'Template', url: '#' },
  { name: 'Resume ATS Checklist', type: 'PDF', module: 'Placement', size: '180 KB', url: '#' },
];

export const DEADLINES = [
  { title: 'CSS Grid Lab', due: 'May 26', status: 'overdue', type: 'Technical', priority: 'high' },
  { title: 'React Hooks Assignment', due: 'May 28', status: 'upcoming', type: 'Technical', priority: 'critical' },
  { title: 'Daily Scrum Update', due: 'May 27', status: 'today', type: 'Scrum', priority: 'high' },
  { title: 'Module 4 Assessment', due: 'Jun 02', status: 'upcoming', type: 'Academic', priority: 'critical' },
];

export const TODAY_PIPELINE = [
  { title: 'Submit scrum update', type: 'Scrum', time: '9:30 AM', status: 'pending' },
  { title: 'Complete CSS Grid lab', type: 'Technical', time: 'Overdue', status: 'overdue' },
  { title: 'DSA — 3 problems', type: 'Interview', time: '2:00 PM', status: 'scheduled' },
  { title: 'Review PR #42 feedback', type: 'Collaboration', time: '4:00 PM', status: 'done' },
  { title: 'Read Module 4 revision notes', type: 'Academic', time: 'Evening', status: 'pending' },
];

export const INSIGHTS = [
  { type: 'positive', text: 'Your React module completion improved by 18% this week' },
  { type: 'warning', text: '3 overdue tasks may affect your leaderboard ranking' },
  { type: 'positive', text: 'Interview readiness score increased by 6 points' },
  { type: 'info', text: 'Attendance and task productivity are strongly aligned (r=0.87)' },
];

export const WEEKLY_PRODUCTIVITY = [
  { day: 'Mon', completed: 3, target: 4 },
  { day: 'Tue', completed: 4, target: 4 },
  { day: 'Wed', completed: 2, target: 4 },
  { day: 'Thu', completed: 5, target: 4 },
  { day: 'Fri', completed: 3, target: 3 },
];

export const COMPLETION_TREND = [
  { week: 'W1', rate: 72 },
  { week: 'W2', rate: 78 },
  { week: 'W3', rate: 81 },
  { week: 'W4', rate: 85 },
  { week: 'W5', rate: 82 },
];

export const INTERVIEW_PREP = [
  { area: 'DSA', progress: 42 },
  { area: 'System Design', progress: 20 },
  { area: 'Communication', progress: 65 },
  { area: 'Aptitude', progress: 55 },
];

export const SPRINT_EXECUTION = [
  { sprint: 'S1', done: 95 },
  { sprint: 'S2', done: 88 },
  { sprint: 'S3', done: 72 },
  { sprint: 'S4', done: 68 },
];

export const PRIORITY_STYLES = {
  critical: 'bg-red-50 text-red-700 border-red-200',
  high: 'bg-brand-orange/10 text-brand-orange border-brand-orange/30',
  medium: 'bg-amber-50 text-amber-700 border-amber-200',
  low: 'bg-gray-50 text-brand-gray border-gray-200',
};

export const STATUS_STYLES = {
  pending: 'bg-gray-100 text-brand-gray border-gray-200',
  in_progress: 'bg-blue-50 text-blue-700 border-blue-200',
  submitted: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  under_review: 'bg-purple-50 text-purple-700 border-purple-200',
  completed: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  overdue: 'bg-red-50 text-red-700 border-red-200',
  blocked: 'bg-brand-charcoal/10 text-brand-charcoal border-gray-300',
};
