/** Student courses workspace seed data */

export const COURSE_OVERVIEW = {
  title: 'Full Stack Development — MERN',
  cohort: 'MERN-B1 · FSD 2026',
  cycle: 'Module Cycle 4',
  status: 'Active Learner',
  progress: 42,
  completedModules: 3,
  totalModules: 12,
  nextUnlock: 'Redux Toolkit',
  nextUnlockDate: '2026-06-05',
  standing: 'Good Standing',
};

export const LEARNING_PIPELINE = {
  activeCourse: 'Full Stack Development',
  currentModule: 'React & State Management',
  sequence: ['HTML/CSS', 'JavaScript', 'React', 'Redux', 'Node.js', 'MongoDB', 'Deployment'],
  sprintWeek: 8,
  facilitator: 'Facilitator John',
  estCompletion: 'Jun 18, 2026',
  moduleHealth: 84,
  velocity: '1.2x',
  placementContribution: 18,
};

export const MODULE_STATUS_STYLES = {
  locked: 'bg-gray-100 text-brand-gray border-gray-200',
  active: 'bg-brand-orange/10 text-brand-orange border-brand-orange/30',
  completed: 'bg-emerald-50 text-emerald-700 border-emerald-100',
  review_pending: 'bg-purple-50 text-purple-700 border-purple-200',
  revision_required: 'bg-amber-50 text-amber-700 border-amber-200',
};

export const MODULES = [
  {
    id: 'm1',
    name: 'HTML/CSS Foundations',
    code: 'FE-101',
    type: 'frontend',
    difficulty: 'Beginner',
    progress: 100,
    facilitator: 'Facilitator John',
    duration: '2 weeks',
    tasks: 8,
    interview: false,
    reviewStatus: 'completed',
    attendanceImpact: 'High',
    github: false,
    stack: ['HTML', 'CSS'],
    status: 'completed',
    content: {
      sessions: ['Intro to Web', 'Flexbox & Grid'],
      pdfs: ['Module Handbook.pdf'],
      docs: ['MDN HTML Reference'],
      exercises: ['Landing Page Lab'],
      assignments: ['Portfolio v1'],
    },
  },
  {
    id: 'm2',
    name: 'JavaScript Core',
    code: 'FE-102',
    type: 'frontend',
    difficulty: 'Intermediate',
    progress: 100,
    facilitator: 'Facilitator John',
    duration: '3 weeks',
    tasks: 12,
    interview: true,
    reviewStatus: 'completed',
    attendanceImpact: 'High',
    github: true,
    stack: ['JavaScript', 'DOM'],
    status: 'completed',
    content: {
      sessions: ['ES6+ Features', 'Async JavaScript'],
      pdfs: ['JS Deep Dive.pdf'],
      docs: ['JavaScript.info'],
      exercises: ['Array Methods Mastery'],
      assignments: ['Todo App v1'],
    },
  },
  {
    id: 'm3',
    name: 'React & State Management',
    code: 'FE-201',
    type: 'frontend',
    difficulty: 'Advanced',
    progress: 68,
    facilitator: 'Facilitator John',
    duration: '4 weeks',
    tasks: 14,
    interview: true,
    reviewStatus: 'review_pending',
    attendanceImpact: 'Critical',
    github: true,
    stack: ['React', 'Hooks'],
    status: 'active',
    content: {
      sessions: ['React Fundamentals', 'Hooks Deep Dive', 'Custom Hooks'],
      pdfs: ['React Patterns.pdf', 'Hooks Cheatsheet.pdf'],
      docs: ['React Official Docs'],
      videos: ['State Management Workshop'],
      exercises: ['Hooks Assignment', 'Context API Lab'],
      github: ['staxhaus-react-starter'],
      assignments: ['Todo App Refactor'],
      reviewPrep: ['Module 4 Assessment Guide'],
      roadmap: ['Week 7-8 Sprint Goals'],
    },
  },
  {
    id: 'm4',
    name: 'Redux Toolkit',
    code: 'FE-202',
    type: 'frontend',
    difficulty: 'Advanced',
    progress: 0,
    facilitator: 'Facilitator John',
    duration: '2 weeks',
    tasks: 6,
    interview: false,
    reviewStatus: 'locked',
    attendanceImpact: 'High',
    github: true,
    stack: ['Redux', 'RTK'],
    status: 'locked',
    content: { sessions: [], pdfs: [], docs: [] },
  },
  {
    id: 'm5',
    name: 'Node.js Backend',
    code: 'BE-101',
    type: 'backend',
    difficulty: 'Advanced',
    progress: 0,
    facilitator: 'Facilitator John',
    duration: '4 weeks',
    tasks: 10,
    interview: true,
    reviewStatus: 'locked',
    attendanceImpact: 'High',
    github: true,
    stack: ['Node.js', 'Express'],
    status: 'locked',
    content: { sessions: [], pdfs: [], docs: [] },
  },
  {
    id: 'm6',
    name: 'MongoDB & Databases',
    code: 'DB-101',
    type: 'database',
    difficulty: 'Intermediate',
    progress: 0,
    facilitator: 'Facilitator John',
    duration: '2 weeks',
    tasks: 6,
    interview: false,
    reviewStatus: 'locked',
    attendanceImpact: 'Medium',
    github: false,
    stack: ['MongoDB', 'Mongoose'],
    status: 'locked',
    content: { sessions: [], pdfs: [], docs: [] },
  },
  {
    id: 'm7',
    name: 'DSA & Problem Solving',
    code: 'DSA-101',
    type: 'DSA',
    difficulty: 'Advanced',
    progress: 35,
    facilitator: 'Placement Cell',
    duration: 'Ongoing',
    tasks: 50,
    interview: true,
    reviewStatus: 'active',
    attendanceImpact: 'Medium',
    github: false,
    stack: ['Algorithms'],
    status: 'active',
    content: {
      sessions: ['Arrays & Strings'],
      pdfs: ['DSA Tracker.xlsx'],
      exercises: ['50 Problem Sheet'],
    },
  },
  {
    id: 'm8',
    name: 'Capstone Project',
    code: 'PRJ-401',
    type: 'project',
    difficulty: 'Advanced',
    progress: 0,
    facilitator: 'Facilitator John',
    duration: '4 weeks',
    tasks: 8,
    interview: true,
    reviewStatus: 'locked',
    attendanceImpact: 'Critical',
    github: true,
    stack: ['MERN'],
    status: 'locked',
    content: { sessions: [], pdfs: [], docs: [] },
  },
];

export const WEEKLY_LEARNING = [
  { week: 'W5', progress: 35 },
  { week: 'W6', progress: 38 },
  { week: 'W7', progress: 40 },
  { week: 'W8', progress: 42 },
];

export const MODULE_VELOCITY = [
  { module: 'M1', weeks: 2 },
  { module: 'M2', weeks: 3 },
  { module: 'M3', weeks: 2.5 },
];

export const ATTENDANCE_VS_LEARNING = [
  { week: 'W5', attendance: 90, learning: 35 },
  { week: 'W6', attendance: 92, learning: 38 },
  { week: 'W7', attendance: 93, learning: 40 },
  { week: 'W8', attendance: 98, learning: 42 },
];

export const EXECUTION_TRACKER = [
  { label: 'GitHub Submissions', value: 24, max: 30 },
  { label: 'Project Milestones', value: 3, max: 8 },
  { label: 'Coding Streak', value: 12, unit: 'days' },
  { label: 'PR Reviews', value: 8, max: 12 },
  { label: 'Deployments', value: 2, max: 5 },
  { label: 'Assignments', value: 11, max: 14 },
];

export const UPCOMING_EVENTS = [
  { title: 'Redux Module Unlock', date: 'Jun 05', type: 'Module' },
  { title: 'Module 4 Assessment', date: 'Jun 02', type: 'Review' },
  { title: 'Mock Interview — React', date: 'Jun 08', type: 'Interview' },
  { title: 'Hooks Assignment Due', date: 'May 28', type: 'Deadline' },
  { title: 'Project Demo Prep', date: 'Jun 15', type: 'Demo' },
];

export const FACILITATOR_INSIGHTS = [
  { type: 'feedback', text: 'Strong React fundamentals. Prioritize CSS Grid before assessment.', author: 'Facilitator John' },
  { type: 'weak', text: 'Async error handling needs improvement.', author: 'Facilitator John' },
  { type: 'strong', text: 'Excellent scrum participation and peer collaboration.', author: 'Facilitator John' },
  { type: 'placement', text: 'Begin DSA intensive after Module 4 clearance.', author: 'Placement Mentor' },
  { type: 'sprint', text: 'Sprint 4 velocity above cohort average.', author: 'Facilitator John' },
];

export const CERTIFICATIONS = [
  { title: 'HTML/CSS Mastery', date: 'Apr 2026', type: 'module' },
  { title: 'JavaScript Core Certified', date: 'May 2026', type: 'module' },
  { title: 'First Deployment', date: 'May 2026', type: 'deployment' },
  { title: '12-Day Learning Streak', date: 'Active', type: 'streak' },
];
